# Generated by Django 4.2.7 on 2023-11-12 04:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Macam_Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Macam_Book', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Judul', models.CharField(max_length=100)),
                ('Tahun_Penerbit', models.CharField(max_length=100)),
                ('Macam_Book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='together.macam_book')),
            ],
        ),
    ]
